#!/usr/bin/env bash
#build-and-test $basename $buildrepo $buildbranch $testrepo "$extrasettings"
#$0             $1        $2         $3           $4        "$5"

basename=$1
buildrepo=$2
buildbranch=$3
testrepo=$4
testbranch=
extrasettings=$5

{cd ~/clones/mo-bundle; cd ..} || {cd ~/clones; gh repo clone MetOffice/mo-bundle}
mv mo-bundle mob-unchanged
gh repo clone MetOffice/mo-bundle || exit 1
mv mo-bundle mob-$basename
cd mob-$basename || exit 1
cd "${buildrepo##*/}" || {gh repo clone $buildrepo || exit 1; cd "${buildrepo##*/}"}
git checkout $buildbranch || exit 1
git fetch --all
git pull || exit 1
cd ../..
./mob-unchanged/bin/bbb ctest st-mob-unchanged
./mob-$basename/bin/bbb ctest st-mob-$basename
cd ~/bin
cmonitor

ctestall "st-$testrepo-ctrl" ~/clones/$testrepo "JEDI_BUILD='"~/cylc-run/mob-unchanged"'"
ctestall "st-$testrepo-$basename" ~/clones/$testrepo "JEDI_BUILD='"~/cylc-run/mob-$basename"' $extrasettings"
cmonitor
