#!/usr/bin/env bash
#gmanage
#$0
echo "Getting latest develop versions"
while IFS= read -r clone; do
	cd ~/clones/$clone || exit 1
	echo "### $clone - develop ###"
	git fetch --all
	git checkout develop || exit 1
	git pull
	echo ""
done < ~/clones/gmanage_members
echo ""
echo "Bringing own branches up-to-date"
while IFS= read -r line; do
	clone2="${line%:*}"
	branch="${line#*:}"
	cd ~/clones/$clone2 || exit 1
	echo "### $clone2/$branch ###"
	branchstatus='none'
	branchstatus=`git checkout $branch || exit 1`
	if [[ $branchstatus == *'branch is ahead'* ]]; then
		git push origin $branch
		echo "--<+>-- $branch pushed! --<+>--"
	fi
	mergestatus=`git merge develop -s ort -X ours -m 'automatic merge from develop'`
	if [[ $mergestatus != *'up to date'* ]]; then
		git push origin $branch
		echo "--<+>-- $branch updated! --<+>--"
	else
		echo 'Already up to date'
	fi
	echo ""
done < ~/clones/gmanage_branches
